# UPDATED PLAYBOOK HEADER
# Proxmox Per-VM Memory Usage (API-First via community.proxmox)
#
# Overview
#   Query and report live memory usage for all VMs and LXCs across one or more Proxmox nodes.
#   Fully API-driven using the community.proxmox collection - no SSH or sudo on nodes required.
#   Safe to run repeatedly; does not modify cluster state.
#
# What this playbook does
#   * Collects all VM and LXC metadata via the Proxmox REST API
#   * Filters out templates
#   * Enriches each item with derived fields:
#       - USED_Gi (used memory in GiB)
#       - MAX_Gi  (configured memory in GiB)
#       - USED_pct (percent of total)
#   * Sorts VMs (running first, then by USED_Gi descending)
#   * Prints a clean, compact list - one line per VM/LXC plus overall totals
#
# Key features
#   * Pure API flow - no Proxmox CLI calls, no SSH into nodes
#   * Works from any Ansible control host with Proxmox API access
#   * Nicely formatted human-readable output suitable for CI logs or terminal use
#   * Supports multiple nodes when pm_node is omitted (auto-discovers all)
#   * Idempotent and read-only
#
# Inputs & variables
#   Proxmox API connection:
#     pm_api_host, pm_api_port, api_user, api_token_id, api_token_secret,
#     pm_api_validate_certs, pm_node (optional)
#
# Output example
#     starhaven/101  dev.bean                        running  4.5Gi/7.9Gi (56.7%)
#     starhaven/106  navidrome-bean                  running  1.0Gi/2.0Gi (49.0%)
#     starhaven/109  rhel-bean                       stopped  0.0Gi/4.0Gi (0.0%)
#     Total: 9 guests | Running: 6 | Stopped: 3 | Used: 13.1 Gi / 55.7 Gi (23.5%)
#
# Quick start
#   1) Ensure Proxmox API token credentials are defined (vaulted or via env vars)
#   2) Define pm_api_host, pm_node, etc. in group_vars/all/main.yml
#   3) Run:
#        ansible-playbook -i inventory/hosts.ini pve_vm_status.yml
#
# Notes & caveats
#   * Requires collection: community.proxmox >= 1.3.0
#   * Read-only - does not start, stop, or modify any VMs
#   * For JSON or structured outputs, wrap in `-o json` callback or use `register` vars
#
# Credit: Thomas Mozdren

---
- name: Proxmox per-VM current usage status (mem + cpu via community.proxmox)
  hosts: localhost
  gather_facts: no

  module_defaults:
    community.proxmox.proxmox_vm_info:
      api_host: "{{ pm_api_host }}"
      api_port: "{{ pm_api_port }}"
      api_user: "{{ api_user }}"
      api_token_id: "{{ api_token_id }}"
      api_token_secret: "{{ api_token_secret | default(pm_api_token_secret) }}"
      validate_certs: "{{ pm_api_validate_certs }}"

  tasks:
    - name: Get VMs/LXCs (all nodes unless pm_node is defined)
      community.proxmox.proxmox_vm_info:
        type: all
        node: "{{ pm_node if (pm_node|default('')|length>0) else omit }}"
        config: none
      register: vm_info

    - name: Start with an empty row list
      set_fact:
        vm_rows: []
      changed_when: false

    - name: Build enriched rows (filter out templates) - append per item
      set_fact:
        vm_rows: >-
          {{ vm_rows
             + [ item | combine({
                   'USED_Gi':  (item.mem    | default(0) | float / 1073741824),
                   'MAX_Gi':   (item.maxmem | default(0) | float / 1073741824),
                   'USED_pct': ((item.maxmem | default(0) | float) > 0)
                                | ternary( (item.mem | default(0) | float / (item.maxmem | float) * 100.0), 0.0),
                   'CPU_pct':  (item.cpu | default(0) | float * 100.0),
                   'vCPUs':    (item.maxcpu | default(item.cpus | default(0)))
                 })
               ]
          }}
      loop: >-
        {{ (vm_info.proxmox_vms | default([]))
           | rejectattr('template','equalto', true) | list }}
      no_log: true
      changed_when: false

    # keep the existing ordering: running first, then by absolute RAM used (GiB) desc
    - name: Order rows (running first, then by USED_Gi desc)
      set_fact:
        vm_sorted: >-
          {{
            (
              (vm_rows | selectattr('status','equalto','running') | list)
              | sort(attribute='USED_Gi', reverse=true)
            )
            +
            (
              (vm_rows | rejectattr('status','equalto','running') | list)
              | sort(attribute='USED_Gi', reverse=true)
            )
          }}
      changed_when: false

    - name: Print simple list (one line per VM, then totals)
      vars:
        total_used_ram_gi: "{{ vm_sorted | map(attribute='USED_Gi') | sum | default(0.0) }}"
        total_max_ram_gi:  "{{ vm_sorted | map(attribute='MAX_Gi')  | sum | default(0.0) }}"
        used_pct_total: "{{ (total_max_ram_gi|float > 0) | ternary((total_used_ram_gi/total_max_ram_gi*100.0), 0.0) }}"
        # CPU summary over running guests only (more meaningful)
        running_list: "{{ vm_sorted | selectattr('status','equalto','running') | list }}"
        running_cpu_sum: "{{ running_list | map(attribute='CPU_pct') | list | sum | default(0.0) }}"
        running_count: "{{ running_list | length }}"
        avg_cpu_running: "{{ running_cpu_sum / ((running_count > 0) | ternary(running_count, 1)) }}"
      block:
        - name: VM line (node/vmid  name  status  CPU%  RAMused/RAMmax)
          debug:
            msg: >-
              {{
                "%s/%s  %-32s  %-7s  CPU:%5.1f%%  RAM: %.1fGi/%.1fGi (%.1f%%)" | format(
                  item.node|default('-'),
                  item.vmid|string,
                  (item.name|default('-'))[:32],
                  item.status|default('-'),
                  item.CPU_pct|default(0.0),
                  item.USED_Gi|default(0.0),
                  item.MAX_Gi|default(0.0),
                  item.USED_pct|default(0.0)
                )
              }}
          loop: "{{ vm_sorted }}"
          loop_control:
            label: "{{ item.node }}/{{ item.vmid }}"
    
        - name: Totals
          debug:
            msg: >-
              {{
                "Total: %d guests | Running: %d | Stopped: %d | RAM Used: %.1f Gi / %.1f Gi (%.1f%%) | Avg CPU (running): %.1f%%" |
                format(
                  (vm_sorted|length),
                  running_count,
                  ((vm_sorted|length) - running_count),
                  total_used_ram_gi, total_max_ram_gi, used_pct_total,
                  avg_cpu_running
                )
              }}